service: abu-api

variablesResolutionMode: 20210219

package:
  individually: true
  excludeDevDependencies: true

plugins:
  - serverless-bundle
  - serverless-s3-local
  - serverless-offline

custom:
  BucketName: ${file(./config/${self:provider.stage}.yml):UPLOAD_BUCKET, 'local'}
  BucketResizePrefix: ${file(./config/${self:provider.stage}.yml):UPLOAD_PREFIX, 'uploads'}
  serverless-offline:
    httpPort: 8061
    lambdaPort: 8066
    noPrependStageInUrl: true
    useChildProcesses: true
  s3:
    port: 8064
    directory: ./.s3-local
    cors: ./resources/s3-cors.xml
  bundle:
    packager: yarn

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  region: ${file(./config/${self:provider.stage}.yml):REGION, 'ap-southeast-1'}
  profile: ${file(./config/${self:provider.stage}.yml):PROFILE, 'default'}
  lambdaHashingVersion: 20201221
  environment:
    TZ: ${file(./config/${self:provider.stage}.yml):TZ, 'Asia/Manila'}
    STAGE: ${self:provider.stage}
    NODE_ENV: ${self:provider.stage}
    DEBUG: ${file(./config/${self:provider.stage}.yml):DEBUG, 'lambda:event,lambda:error'}
    COG_POOL_ID: ${file(./config/${self:provider.stage}.yml):COG_POOL_ID, 'pool-id'}
    COG_ACCESS_KEY_ID: ${file(./config/${self:provider.stage}.yml):COG_ACCESS_KEY_ID, 'access-key-id'}
    COG_SECRET_ACCESS_KEY: ${file(./config/${self:provider.stage}.yml):COG_SECRET_ACCESS_KEY, 'secret-key-id'}
    DDB_REGION: ${file(./config/${self:provider.stage}.yml):REGION, 'ap-southeast-1'}
    DDB_ENDPOINT: ${file(./config/${self:provider.stage}.yml):DDB_ENDPOINT, ''}
    DDB_TABLE: ${file(./config/${self:provider.stage}.yml):DDB_TABLE, 'abu-local'}
    S3_BUCKET: ${self:custom.BucketName}
    S3_BUCKET_PREFIX: ${self:custom.BucketResizePrefix}
    S3_BASE_URL: ${file(./config/${self:provider.stage}.yml):UPLOAD_BASE_URL, 'http://localhost:8064/local'}
    PAGINATION_SECRET: ${file(./config/${self:provider.stage}.yml):PAGINATION_SECRET, 'some-random-key'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::${self:custom.BucketName}"
            - "arn:aws:s3:::${self:custom.BucketName}/*"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DDB_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DDB_TABLE}/*"

functions: ${file(./functions.js)}

resources:
  Resources:
    ApiGatewayAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: cognito-authorizer
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - Fn::ImportValue: AbuCognitoUserPoolArn-${self:provider.stage}
