service: abu-database

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: ${file(../config/${self:provider.stage}.yml):REGION}
  profile: ${file(../config/${self:provider.stage}.yml):PROFILE}
  environment:
    TZ: ${file(../config/${self:provider.stage}.yml):TZ, "Asia/Manila"}

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: abu-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: pk2
            AttributeType: S
          - AttributeName: sk2
            AttributeType: S
          - AttributeName: pk3
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: "GSI"
            KeySchema:
              - AttributeName: "pk2"
                KeyType: "HASH"
              - AttributeName: "sk2"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
          - IndexName: "GSI2"
            KeySchema:
              - AttributeName: "pk3"
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"
