service: abu-api-admin-content

projectDir: ../../

plugins:
  - serverless-bundle
  - serverless-offline

custom:
  BucketName: ${file(./config/${self:provider.stage}.yml):S3_BUCKET, 'local'}
  BucketResizePrefix: ${file(./config/${self:provider.stage}.yml):S3_BUCKET_PREFIX, 'uploads'}
  bundle:
    caching: false
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp && npm install --arch=x64 --platform=linux sharp

package:
  individually: true

provider:
  name: aws
  stage: ${opt:stage, 'local'}
  region: ${file(../../config/${self:provider.stage}.yml):REGION, 'ap-southeast-1'}
  profile: ${file(../../config/${self:provider.stage}.yml):PROFILE, 'default'}
  runtime: nodejs12.x
  memorySize: 256
  timeout: 30
  lambdaHashingVersion: 20201221
  environment:
    TZ: ${file(../../config/${self:provider.stage}.yml):TZ, 'Asia/Singapore'}
    STAGE: ${self:provider.stage}
    NODE_ENV: ${self:provider.stage}
    DEBUG: ${file(../../config/${self:provider.stage}.yml):DEBUG, 'lambda:event,lambda:error'}
    DDB_REGION: ${file(../../config/${self:provider.stage}.yml):REGION, 'ap-southeast-1'}
    DDB_ENDPOINT: ${file(../../config/${self:provider.stage}.yml):DDB_ENDPOINT, ''}
    DDB_TABLE: ${file(../../config/${self:provider.stage}.yml):DDB_TABLE, 'abu-local'}
    S3_BUCKET: ${self:custom.BucketName}
    S3_BUCKET_PREFIX: ${self:custom.BucketResizePrefix}
    S3_BASE_URL: ${file(./config/${self:provider.stage}.yml):S3_BASE_URL, 'http://localhost:8064/local'}
    PAGINATION_SECRET: ${file(./config/${self:provider.stage}.yml):PAGINATION_SECRET, 'some-random-key'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DDB_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DDB_TABLE}/*"
        - Effect: Allow
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::${self:custom.BucketName}"
            - "arn:aws:s3:::${self:custom.BucketName}/*"

functions: ${file(./functions.yml)}

resources:
  Resources:
    ApiGatewayAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: cognito-authorizer
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - ${file(../../config/${self:provider.stage}.yml):COG_POOL_ARN}
