name: Validate API Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/api**/**"
      - "packages/model/**"
      - "packages/authorizer/**"
      - "packages/cognito/**"
      - "packages/helper/**"
      - "!**/**.md"
      - "!docs/**"
      - "!packages/cms/**"
      - "!infra/**"
      - "!scripts/**"
      - "!config/**"
  workflow_dispatch:

jobs:
  build:
    name: Build and Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            **/node_modules
            ~/.cache/Cypress
            **/.serverless
            **/.webpack
          key: ${{ runner.os }}-build-app-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-app-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-build-app-${{ env.cache-name }}-
            ${{ runner.os }}-build-app-
            ${{ runner.os }}-

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      - name: Cache DynamoDB docker images
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8062
          cors: "*"

      - name: Create DynamoDB Table
        working-directory: infra
        run: yarn workspace infra ddb:init

      - name: Smoke Test
        run: yarn build:api

      - name: Test API
        run: yarn test:api

      - name: Coverage Report
        run: yarn coverage:api

      - uses: actions/upload-artifact@v1
        with:
          name: Coverage Report
          path: coverage
